name: Package Application with Pyinstaller

on: 
  push:
    # only trigger on branches, not on tags
    branches: '**'
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Windows Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./

    - uses: actions/upload-artifact@v3
      with:
        name: WindowsBuild
        path: ./dist/windows/

    - name: Package Linux Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: ./

    - uses: actions/upload-artifact@v3
      with:
        name: LinuxBuild
        path: ./dist/linux/

