name: Package Application with Pyinstaller

on: 
  push:
    # only trigger on branches, not on tags
    branches: '**'
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./

    - uses: actions/upload-artifact@v3
      with:
        name: Application
        path: ./dist/windows/main.exe
